In [12]:
# ques 1
import numpy as np

a = np.array([1, 7, 3, 10, 14, 76, 4])

n = len(a)
for i in range(n):
    for j in range(i + 1, n):
        if (a[i] + a[j]) % 7 == 0:
            print(f"Index: ({i}, {j}), Values: ({a[i]}, {a[j]})")


Index: (0, 5), Values: (1, 76)
Index: (1, 4), Values: (7, 14)
Index: (2, 6), Values: (3, 4)
Index: (3, 6), Values: (10, 4)


In [13]:
# ques 2
import numpy as np

A = np.array([[1, 2, 0],
              [0, 5, 6],
              [7, 0, 9]])

B = np.array([[5, 6, 7],
              [7, 8, 9],
              [1, 2, 3]])

A_inv = np.linalg.inv(A)

dot_product = np.dot(A_inv, B)

elt_product = A_inv * B

print("Inverse of A (A_inv):\n",A_inv)
print("\nDot product of A_inv and B:\n",dot_product)
print("\nElementwise multiplication of A_inv and B:\n",elt_product)


Inverse of A (A_inv):
 [[ 0.34883721 -0.13953488  0.09302326]
 [ 0.3255814   0.06976744 -0.04651163]
 [-0.27131783  0.10852713  0.03875969]]

Dot product of A_inv and B:
 [[ 0.86046512  1.1627907   1.46511628]
 [ 2.06976744  2.41860465  2.76744186]
 [-0.55813953 -0.68217054 -0.80620155]]

Elementwise multiplication of A_inv and B:
 [[ 1.74418605 -0.8372093   0.65116279]
 [ 2.27906977  0.55813953 -0.41860465]
 [-0.27131783  0.21705426  0.11627907]]


In [14]:
# ques 3
import numpy as np
import pandas as pd

data = np.array([
    [1, 2, 3, 4, 5],
    [1, 8, 2, 10, 11],
    [4, 5, 6, 7, 8],
    [7, 8, 9, 10, 11],
    [7, 18, 19, 10, 11]
])

df = pd.DataFrame(data, columns=['A', 'B', 'C', 'D', 'E'])

df2 = df.sort_values(by='C')

print("First two rows of df2:")
print(df2.head(2))
print("\nLast two rows of df2:")
print(df2.tail(2))

df2_values = df2.values
print("\ndf2 values as NumPy array:")
print(df2_values)

First two rows of df2:
   A  B  C   D   E
1  1  8  2  10  11
0  1  2  3   4   5

Last two rows of df2:
   A   B   C   D   E
3  7   8   9  10  11
4  7  18  19  10  11

df2 values as NumPy array:
[[ 1  8  2 10 11]
 [ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]
 [ 7 18 19 10 11]]


In [15]:
# ques 4
import numpy as np

A = np.array([[1, 2, 0],
              [0, 5, 6],
              [7, 0, 9]])

eigenvalues, eigenvectors = np.linalg.eig(A)

spectral_radius = np.max(np.abs(eigenvalues))

print("Eigenvalues of A:",eigenvalues)
print("Spectral radius of A:",spectral_radius)


Eigenvalues of A: [10.5740355 +0.j          2.21298225+2.70229602j  2.21298225-2.70229602j]
Spectral radius of A: 10.57403549813147


In [11]:
# ques 5
import numpy as np

B = np.array([[5, 6, 7],
              [7, 8, 9],
              [1, 2, 3]])

U, S, Vt = np.linalg.svd(B, full_matrices=False)

Sigma = np.diag(S)

print("U:\n", U)
print("\nSigma (diagonal matrix):\n", Sigma)
print("\nVt:\n", Vt)

B_recon = U @ Sigma @ Vt

acc = np.allclose(B, B_recon, atol=1e-10)
print("\n\nReconstruction accuracy : ", acc)

sigma_max = S.max()
sigma_min = S.min()
condition_number = sigma_max / sigma_min
print("\nSpectral condition number (K2(B)):", condition_number)


U:
 [[-0.58909693  0.10053691 -0.80178373]
 [-0.78215124 -0.32019549  0.53452248]
 [-0.20298829  0.94200169  0.26726124]]

Sigma (diagonal matrix):
 [[1.78028049e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.02963004e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.47181129e-15]]

Vt:
 [[-0.48439174 -0.57281806 -0.66124437]
 [-0.77375576 -0.07219979  0.62935619]
 [ 0.40824829 -0.81649658  0.40824829]]


Reconstruction accuracy :  True

Spectral condition number (K2(B)): 1.2095847478372948e+16
